### PR TITLE
Forms

### PR DESCRIPTION
**Pull request by AlexRS90**
For this PR I:
 ✅  Create forms to perform the following functions:
      ✔️  Creates a Post on behalf of the current_user. 📄 
      ✔️  Create a comment on behalf of the current_user. ✍️ 
✅  Allow Users to add likes to Posts. 👍 

Note: ⬇️  ⚠️ ⬇️  ⚠️ ⬇️ 

Kindly follow the instructions in the README.md file to add initial users to the database.
Happy Coding! 👨‍💻

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
## Hi @AlexRS90, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Major highlights for your project:
- No linter errors
- Followed git workflow
- Good README


## Required Changes ♻️
- [x] I am getting this error while seeding the server
mssk this is coming from your `seed` file



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by AlexRS90** [comment]
Hi @DeliceLydia, thanks for the feedback, could you give me a little more explanation about the error, because I'm not getting this error on my side.

I added manually a new `post` from the rails terminal with the same command from the `seed` file and is working as expected

Captura de Pantalla 2022-02-25 a la(s) 14 51 34

**Review by bimbolabuari — APPROVED** [review]
# Project Approved 🚀

Hi @AlexRS90 🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AlexRS90** [comment]
Thanks @bimbolabuari

**Pull request merged**
